require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'   #16/6/2022_maps - geolocation để có thể dùng react-native-maps thiết bị phải trên ios12
install! 'cocoapods', :deterministic_uuids => false

target 'demo_rn_feature' do

  # React Native Maps dependencies  16/6/2022_maps --> Phục vụ cho map 
    rn_maps_path = '../node_modules/react-native-maps'
    pod 'react-native-google-maps', :path => rn_maps_path
  #####

  # 28/6/2022_fileSystem  ---> phục vụ quản lý file 
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  # end

  # 6/7/2022_RN-fetch-blob  ---> Phục vụ download/upload file + quản lý file
  pod 'react-native-fetch-blob',
  :path => '../node_modules/react-native-fetch-blob'
  # end

  #  19/6/2022_QRcode 
  permissions_path = '../node_modules/react-native-permissions/ios'

  # ###### 27/6/2022_permission   TẤT CẢ CÁC DÒNG   pod 'Permission-...'  Đều là các quyền của ứng dụng được cấp phép
   pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  #  Có thể thêm rất nhiều quyền : với các dòng tương tự như trên 
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  # end
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'demo_rn_featureTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
